services:
  tempo:
    container_name: tempo
    image: grafana/tempo:2.10.0
    restart: on-failure
    command:
      - -config.file=/etc/tempo-config/tempo.yaml
    volumes:
      - ./config/tempo:/etc/tempo-config
      - ./data/tempo/tmp:/tmp/tempo          # для WAL, блоков и генератора
      - ./data/tempo/var:/var/tempo          # для /var/tempo/traces    
    ports:
      - '3200:3200'
#      - '4317:4317'
#      - '4318:4318'
    depends_on:
      - loki
      - mimir
      - pyroscope

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: on-failure
    volumes:
      - ./data/loki:/loki                   # том для данных (по умолчанию /loki)
    ports:
      - '3100:3100'

  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:latest
    restart: on-failure
    volumes:
      - ./data/pyroscope:/var/lib/pyroscope # том для данных (по умолчанию /var/lib/pyroscope)
    ports:
      - '4040:4040'
